CREATE DATABASE NEWUSER_prod;
CREATE DATABASE NEWUSER_test;
CREATE USER 'NEWUSER'@'localhost' IDENTIFIED BY 'PASSWD';
GRANT ALL PRIVILEGES ON NEWUSER_prod.* to 'NEWUSER'@'localhost';
GRANT ALL PRIVILEGES ON NEWUSER_test.* to 'NEWUSER'@'localhost';
FLUSH PRIVILEGES;
